<?=$this->html->doctype();?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Hazaar MVC</title>

    <?=$this->import(); ?>

</head>
<body>

    <div class="ide">
        <div class="ide-toolbar">
            <img src="file/console/images/hazaar-icon-white.png" class="ide-icon" />
            <div class="ide-brand">Hazaar MVC Console</div>
            <div class="ide-menu">
                <div class="ide-menu-item">File</div>
                <div class="ide-menu-item">Edit</div>
                <div class="ide-menu-item">View</div>
                <div class="ide-menu-item">Help</div>
            </div>
            <div class="ide-settings">
                <i class="fa fa-cog"></i>
            </div>
        </div>
        <div class="ide-main">
            <div class="ide-drawer left">
                <div class="bar">
                    <div class="bar-item">File Manager</div>
                    <div class="bar-item">Project</div>
                </div>
                <div class="panel">
                    <div class="ide-tree">
                        <div class="tree-node" id="testNode">
                            <div class="tree-node-icon fa fa-line-chart"></div>
                            <div class="tree-node-label">Metrics</div>
                        </div>
                        <div class="tree-node" id="testNode">
                            <div class="tree-node-icon fa fa-wrench"></div>
                            <div class="tree-node-label">Configuration</div>
                        </div>
                        <div class="tree-node" id="testNode">
                            <div class="tree-node-icon fa fa-cog"></div>
                            <div class="tree-node-label">System</div>
                        </div>
                        <div class="tree-node" id="testNode">
                            <div class="tree-node-icon fa fa-plus"></div>
                            <div class="tree-node-label">Warlock</div>
                            <div class="tree-node-items">
                                <div class="tree-node" id="testNode">
                                    <div class="tree-node-icon fa fa-magic"></div>
                                    <div class="tree-node-label">Status</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ide-main-panel">
                <div class="ide-tab-bar">
                    <div class="tab-bar-item">hazaar.js</div>
                    <div class="tab-bar-item active">content.phtml</div>
                    <div class="tab-bar-item">index.php</div>
                </div>
                <div class="ide-tab-content">Content here...</div>
            </div>
        </div>
    </div>

    <?=$this->post();?>

</body>
</html>
