<?=$this->html->doctype();?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Hazaar MVC</title>

    <?=$this->import(); ?>

</head>
<body>

    <div class="ide">
        <div class="ide-toolbar">
            <img src="file/console/images/hazaar-icon-white.png" class="ide-icon"></img>
            <div class="ide-brand">Hazaar MVC Console</div>
            <div class="ide-menu">
                <div class="ide-menu-item">File</div>
                <div class="ide-menu-item">Edit</div>
                <div class="ide-menu-item">View</div>
                <div class="ide-menu-item">Help</div>
            </div>
            <div class="ide-settings">
                <i class="fa fa-cog"></i>
            </div>
        </div>
        <div class="ide-main">
            <div class="ide-drawer left">
                <div class="bar">
                    <div class="bar-item">File Manager</div>
                    <div class="bar-item">Project</div>
                </div>
                <div class="panel"></div>
            </div>
            <div class="ide-main-panel">
                <div class="ide-tab-bar">
                    <div class="tab-bar-item">hazaar.js</div>
                </div>
                <div class="ide-tab-content">Content here...</div>
            </div>
        </div>
    </div>

    <?=$this->post();?>

</body>
</html>
