<?=$this->html->doctype();?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Hazaar MVC</title>
    <?=$this->import(); ?>
</head>
<body>
    <div class="ide" id="ide" data-view="home">
        <div class="ide-nav-panel">
            <img src="file/console/images/hazaar-icon-white.png" class="ide-icon" />
            <hr/>
            <ul class="ide-nav" id="mainMenu">
                <li class="clickable" data-toggle="home" title="Home"><i class="fas fa-home"></i>
                <li class="clickable" data-toggle="code" title="Code"><i class="fas fa-code"></i>
                <li class="clickable" data-toggle="plugins" title="Plug-ins"><i class="fas fa-plug"></i>
            </ul>
            <hr/>
            <ul class="ide-nav">
                <li class="clickable" title="Support chat"><i class="fas fa-comment-dots"></i>
            </ul>
            <ul class="ide-nav ide-settings" title="Settings">
                <li class="clickable" title="Settings"><i class="fas fa-cog"></i>
                <li class="clickable" title="Help"><i class="fas fa-question-circle"></i>
            </ul>
        </div>
        <div class="ide-toolbar">
            <div class="ide-menu" data-view="home">
                <div class="ide-menu-item"><i class="fas fa-sliders-h"></i>Settings</div>
                <div class="ide-menu-item"><i class="fas fa-layer-group"></i>Workspaces</div>
            </div>
            <div class="ide-menu" data-view="code">
                <div class="ide-menu-item"><i class="fas fa-file"></i>File</div>
                <div class="ide-menu-item"><i class="fas fa-edit"></i>Edit</div>
                <div class="ide-menu-item"><i class="fas fa-search"></i>Find</div>
                <div class="ide-menu-item"><i class="fas fa-layer-group"></i>View</div>
                <div class="ide-menu-item"><i class="fas fa-chevron-circle-right"></i>Goto</div>
                <div class="ide-menu-item"><i class="fas fa-tools"></i>Tools</div>
                <div class="ide-menu-item"><i class="fas fa-play-circle"></i>Run</div>
            </div>
        </div>
        <div class="ide-content">
            <div class="content-menu" id="consoleTreeMenu"></div>
            <div class="content-main" id="consoleTabs"><div class="content-float">What would you like to do today?</div></div> 
        </div>
    </div>
    <?=$this->post();?>
</body>
</html>
