
<div class="container-fluid text-dark">
    <div class="card">
        <div class="card-header">Models</div>
        <div class="card-body">
            <?=$this->partial('mvc_items', array('items' => $this->models));?>
        </div>
        <div class="card-footer">
            <button onclick="doIt()">Do the thing!</button>
        </div>
    </div>
</div>

<script>
    $console.ready(function(){
        console.log('Ready');
    }).focus(function(){
        console.log('Model Focus');
    });
</script>